- name: variable demo
  hosts: all
  vars:
    URL: cloudblitz.in  # Global Variable
  tasks:
    - debug:
        msg: Hello World, {{ URL }}
      vars:
        URL: local.cloudblitz.in  # Local Variable
    - debug:
        msg: My URL is, {{ URL }}

# Variable Priorities
# 1. cli vars
# 2. local vars
# 3. Global Vars