- name: variable demo
  hosts: all
  vars:
    URL: cloudblitz.in  
  tasks:
    - debug:
        msg: Hello World, {{ URL }}
      vars:
        URL: local.cloudblitz.in
    - debug:
        msg: My URL is, {{ URL }}
