- name: my first playbook
  hosts: all
  gather_facts: true
  tasks:
    - debug:
        msg: I love Apple
    - debug:
        msg: I love Stratberry
    - debug:
        msg: I love Banana
    - debug:
        msg: I love Apple
    - debug:
        msg: I love Apple