- name: my first playbook
  hosts: all
  gather_facts: true
  tasks:
    - debug:
        msg: I love {{item}}
      loop:
        - Apple
        - Pineapple
        - mango
        - straberry
        - orange

