- name: my first playbook
  hosts: all
  become: true
  tasks:
    - debug:
        msg: Hello World
    
    - copy:
        src: index.html
        dest: /opt/copy.html

    - template:
        src: index.html
        dest: /opt/template.html