- name: Install Java
  package:
    name: "{{JAVA}}"
    state: present

- name: Download Tomcat
  get_url:
    url: "{{TOMCAT_URL}}"
    dest: /opt

- name: Extract Tomcat
  unarchive:
    src: /opt/{{TOMCAT_ARCHIVED}}
    dest: /opt
    remote_src: yes

- name: Start catalina.sh
  shell: /opt/{{TOMCAT_DIR}}/bin/catalina.sh run

