- name: Install Java
  package:
    name: "{{JAVA}}"
    state: present

- name: Download Tomcat
  get_url:
    url: "{{TOMCAT_URL}}"
    dest: /opt

- name: Extract Tomcat
  unarchive:
    src: /opt/
    dest: /opt
    remote_src: yes

- name: Start catalina.sh
  shell: /opt/apache-tomcat-9.0.93/bin/catalina.sh run

