- name: Install Java
  package:
    name: openjdk-17-jre
    state: present

- name: Download Tomcat
  get_url:
    url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.93/bin/apache-tomcat-9.0.93.tar.gz
    dest: /opt

- name: Extract Tomcat
  unarchive:
    src: /opt/apache-tomcat-9.0.93.tar.gz
    dest: /opt

- name: Start catalina.sh
  shell:
    
